version: '3.6'
services:
  php:
    build:
      context: .build/docker/php
    container_name: demo-doctrine-php
    networks:
      - demo_doctrine_network
    volumes:
      - ./:/code:cached
      - .build/docker/php/php.ini:/usr/local/etc/php/conf.d/docker-wrs.ini
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal idekey=PHPSTORM"
      PHP_IDE_CONFIG: "serverName=Docker"
  mysql:
    image: mysql:8
    container_name: demo-doctrine-mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - demo_doctrine_network
    ports:
      - "3390:3306"
    environment:
      - MYSQL_DATABASE=demo-doctrine
      - MYSQL_ROOT_PASSWORD=root
networks:
  demo_doctrine_network:
    driver: bridge
